---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-beginner
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-beginner
  template:
    metadata:
      labels:
        app: node-beginner
    spec:
      containers:
        -
          image: thihenos/docker-node:0.2
          name: app
